#!/bin/bash
# Author: Paulo Jeronimo (@paulojeronimo, pj@paulojeronimo.info)
#
# Some useful references to things coded in this script:
# 1) http://www.unixmantra.com/2014/03/a-simple-way-to-send-multiple-line-commands-over-ssh.html
# 2) http://linuxcommando.blogspot.com.br/2008/10/how-to-disable-ssh-host-key-checking.html
set +x
source ~/.tv || exit 1

SCRIPT=/tmp/access-${MY_USER}-screen.`date +%s`

ssh -T $TV_USER@$TV_HOST <<EOF
cat <<'EOF2' > $SCRIPT
#!/bin/bash
set +x
read -s -p "Enter \"$MY_USER\" password for \"$MY_HOST\": " SSHPASS
echo; export SSHPASS
sshpass -e ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
-L $VNC_PORT:localhost:$VNC_PORT $MY_USER@$MY_HOST \
"x11vnc -localhost -rfbport $VNC_PORT -viewonly -display $MY_DISPLAY"
EOF2
chmod +x $SCRIPT
EOF

ssh -t $TV_USER@$TV_HOST $SCRIPT
