#!/bin/bash
# Author: Paulo Jeronimo (@paulojeronimo, pj@paulojeronimo.info)
set +x
source ~/.tv || exit 1

op=$1
case $op in
   on)
      ssh $TV_USER@$TV_HOST "export DISPLAY=$TV_DISPLAY; vinagre localhost --vnc-scale -f &" & ;;
   off)
      ssh $TV_USER@$TV_HOST 'pkill vinagre' ;;	
   *) 
      echo "You must specify \"on\" or \"off\"!"
      exit 1 ;;
esac
